enum NivelMenu {
    INICIAL, 
    MESA, 
    MESA_ADD_PLAYER, 
    MESA_INIT_GAME, 
    ESTATISTICA, 
    SOBRE,
    ACAO, 
    ESTATISTICA_GERAL,
    ESTATISTICA_NOME,
    GAME_ROUBAR,
    GAME_DISCARTE,
    GAME_PASSAR_VEZ,
    VOLTAR, 
    SAIR
}